In [10]:
conn = psycopg2.connect(
    host="jrvs-psql",
    port=5432,
    user="postgres",
    password="password",
    database="postgres"
)

In [27]:
import pandas as pd
import numpy as np
import psycopg2

conn = psycopg2.connect(
    host="jrvs-psql",  
    port=5432,
    user="postgres",
    password="password",
    database="postgres"
)

df = pd.read_sql("SELECT * FROM retail;", conn)

In [28]:
df.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [29]:
df.tail()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   invoice_no    1067371 non-null  object
 1   stock_code    1067371 non-null  object
 2   description   1062989 non-null  object
 3   quantity      1067371 non-null  int64
 4   invoice_date  1067371 non-null  datetime64[ns]
 5   unit_price    1067371 non-null  float64
 6   customer_id   824364 non-null   float64
 7   country       1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [20]:
df.isnull().sum()

invoice_no           0
stock_code           0
description       4382
quantity             0
invoice_date         0
unit_price           0
customer_id     243007
country              0
dtype: int64

In [21]:
df.describe()

           quantity    unit_price    customer_id
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359440e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [31]:
df['country'].unique()

array(['United Kingdom', 'France', 'USA', 'Belgium', 'Australia', 'EIRE',
       'Germany', 'Portugal', 'Japan', 'Denmark', 'Poland', 'Nigeria',
       'Netherlands', 'Spain', 'Channel Islands', 'Italy', 'Cyprus',
       'Greece', 'Norway', 'Austria', 'Sweden', 'United Arab Emirates',
       'Finland', 'Switzerland', 'Unspecified', 'Malta', 'Bahrain', 'RSA',
       'Bermuda', 'Hong Kong', 'Singapore', 'Thailand', 'Israel',
       'Lithuania', 'West Indies', 'Lebanon', 'Korea', 'Brazil', 'Canada',
       'Iceland', 'Saudi Arabia', 'Czech Republic', 'European Community'],
      dtype=object)

In [24]:
len(df)

1067371